# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      - name: Installing poetry
        run: |
          pip install poetry wheel
      - name: Display poetry version
        run: |
          poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Black linting
        run: |
          poetry run black --check .
      - name: Test with pytest
        run: |
          poetry run pytest .
      - name: Build wheel
        run: |
          wheel_filename=$(poetry build -f wheel | grep -P -o 'codstatstracker[-\d\w.]+')
          wheel_file=($pwd)/dist/$wheel_filename
          print "$wheel_filename"
          echo "wheel_file=$wheel_file"
          echo "wheel_file=$wheel_file" >> $GITHUB_ENV
      - name: Archive wheel as artifact
        uses: actions/upload-artifact@v2
        with:
          name: codstattracker-wheel
          path: ${{ env.wheel_file }}
