name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build package in container
        run: |
          docker build -t codstattracker .
      - name: Copy artifact
        id: cp_artifact
        run: |
          set -e ; \
          mkdir -p result ; \
          mount_args="--mount type=bind,source=$(pwd)/result,target=/mnt/" ; \
          docker run $mount_args codstattracker sh -c 'cp dist/$(cat dist/wheel_name.txt) /mnt' ; \
          wheel_name=$(docker run codstattracker cat dist/wheel_name.txt) ; \
          cp result/$wheel_name . ; \
          echo "::set-output name=wheel_name::$wheel_name"
      - name: Deploy to pythonanywhere.com
        env:
          PA_DEPLOY_SECRET: ${{ secrets.PA_DEPLOY_SECRET }}
          wheel_name: ${{ steps.cp_artifact.outputs.wheel_name }}
        run: |
          set -e ; \
          echo $wheel_name ; \
          curl -F "$wheel_name=@$wheel_name" -u $PA_DEPLOY_SECRET https://danields761.pythonanywhere.com/upload

      - name: Archive wheel as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.cp_artifact.outputs.wheel_name }}
          path: ${{ steps.cp_artifact.outputs.wheel_name }}
